[package]
name = "goldentooth-mcp"
version = "0.1.0"
edition = "2024"
authors = ["Nathan Douglas <github@darkdell.net>"]
description = "MCP server for Goldentooth cluster management"
license = "Unlicense"

[dependencies]
rmcp = { version = "0.2.0", features = ["server"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "io-std"] }
